Repository CAKES-coding/swe574-group2, pull requests merged in 2021-11, with the labels that each got.

#52 Register and login
  Project/Wikode/Wikode/settings.py
  Project/Wikode/Wikode/urls.py
  Project/Wikode/Wikode/wsgi.py
  Project/Wikode/templates/wikodeApp/base.html
  Project/Wikode/templates/wikodeApp/homePage.html
  Project/Wikode/templates/wikodeApp/login.html
  Project/Wikode/templates/wikodeApp/registration.html
  Project/Wikode/templates/wikodeApp/registrationRequests.html
  Project/Wikode/templates/wikodeApp/userList.html
  Project/Wikode/wikodeApp/admin.py
  Project/Wikode/wikodeApp/forms.py
  Project/Wikode/wikodeApp/models.py
  Project/Wikode/wikodeApp/static/wikodeApp/css/navbar.css
  Project/Wikode/wikodeApp/static/wikodeApp/css/styles.css
  Project/Wikode/wikodeApp/tests.py
  Project/Wikode/wikodeApp/urls.py
  Project/Wikode/wikodeApp/views.py
Labels: enhancement, effort: 2, priority: High, testing

#65 Fetch article from entrez
  Project/Wikode/Wikode/wsgi.py
  Project/Wikode/templates/wikodeApp/articlesSaved.html
  Project/Wikode/templates/wikodeApp/base.html
  Project/Wikode/templates/wikodeApp/fetchArticles.html
  Project/Wikode/wikodeApp/forms.py
  Project/Wikode/wikodeApp/models.py
  Project/Wikode/wikodeApp/static/wikodeApp/css/bootstrap-tagsinput.css
  Project/Wikode/wikodeApp/static/wikodeApp/css/grid.css
  Project/Wikode/wikodeApp/static/wikodeApp/js/bootstrap-tagsinput.js
  Project/Wikode/wikodeApp/static/wikodeApp/js/index.js
  Project/Wikode/wikodeApp/urls.py
  Project/Wikode/wikodeApp/utils/articleManager.py
  Project/Wikode/wikodeApp/utils/fetchArticles.py
  Project/Wikode/wikodeApp/views.py
Labels: enhancement, backend, effort: 2, frontend

#70 Enhance frontend of Login and Register pages
  Project/Wikode/templates/wikodeApp/base.html
  Project/Wikode/templates/wikodeApp/login.html
  Project/Wikode/templates/wikodeApp/registration.html
  Project/Wikode/wikodeApp/views.py
Labels: enhancement, effort: 1, frontend

#72 Develop to main
  Project/Wikode/Wikode/wsgi.py
  Project/Wikode/templates/wikodeApp/articlesSaved.html
  Project/Wikode/templates/wikodeApp/base.html
  Project/Wikode/templates/wikodeApp/fetchArticles.html
  Project/Wikode/templates/wikodeApp/login.html
  Project/Wikode/templates/wikodeApp/registration.html
  Project/Wikode/wikodeApp/forms.py
  Project/Wikode/wikodeApp/models.py
  Project/Wikode/wikodeApp/static/wikodeApp/css/bootstrap-tagsinput.css
  Project/Wikode/wikodeApp/static/wikodeApp/css/grid.css
  Project/Wikode/wikodeApp/static/wikodeApp/js/bootstrap-tagsinput.js
  Project/Wikode/wikodeApp/static/wikodeApp/js/index.js
  Project/Wikode/wikodeApp/urls.py
  Project/Wikode/wikodeApp/utils/articleManager.py
  Project/Wikode/wikodeApp/utils/fetchArticles.py
  Project/Wikode/wikodeApp/views.py
  external_resources/ProjectGhantChart.png
Labels: backend, effort: 1, frontend

#71 Feature/basic article search
  Project/Wikode/Wikode/settings.py
  Project/Wikode/Wikode/urls.py
  Project/Wikode/templates/wikodeApp/articleDetail.html
  Project/Wikode/templates/wikodeApp/base.html
  Project/Wikode/templates/wikodeApp/searchResults.html
  Project/Wikode/wikodeApp/forms.py
  Project/Wikode/wikodeApp/models.py
  Project/Wikode/wikodeApp/static/wikodeApp/js/typeahead.js
  Project/Wikode/wikodeApp/tests.py
  Project/Wikode/wikodeApp/urls.py
  Project/Wikode/wikodeApp/utils/__init__.py
  Project/Wikode/wikodeApp/utils/textSearch.py
  Project/Wikode/wikodeApp/utils/wikiManager.py
  Project/Wikode/wikodeApp/views.py
Labels: enhancement, backend, effort: 2, priority: High, frontend

#79 Feature/article filtering and sorting
  Project/Wikode/requirements.txt
  Project/Wikode/templates/wikodeApp/base.html
  Project/Wikode/templates/wikodeApp/homePage.html
  Project/Wikode/templates/wikodeApp/searchAndFilterBox.html
  Project/Wikode/templates/wikodeApp/searchResults.html
  Project/Wikode/wikodeApp/forms.py
  Project/Wikode/wikodeApp/tests.py
  Project/Wikode/wikodeApp/utils/textSearch.py
  Project/Wikode/wikodeApp/views.py
Labels: enhancement, backend, effort: 3, priority: Blocker, testing, frontend

#81 Feature/article detail page
  Project/Wikode/templates/wikodeApp/articleDetail.html
  Project/Wikode/templates/wikodeApp/base.html
  Project/Wikode/wikodeApp/models.py
  Project/Wikode/wikodeApp/static/wikodeApp/js/articleDetail.js
  Project/Wikode/wikodeApp/tests.py
  Project/Wikode/wikodeApp/views.py
Labels: enhancement, backend, effort: 5, testing, frontend

#84 Fix naming bug for article detail page. #83
  Project/Wikode/wikodeApp/models.py
  Project/Wikode/wikodeApp/views.py
Labels: bug, backend, effort: 1

#94 It was not possible to make normal user admin
  Project/Wikode/wikodeApp/views.py
Labels: bug, effort: 1
