Repository CAKES-coding/swe574-group2, pull requests merged in 2021-12, with the labels that each got.

#104 Bug/pagination error
  Project/Wikode/Wikode/settings.py
  Project/Wikode/templates/wikodeApp/searchResults.html
  Project/Wikode/wikodeApp/forms.py
  Project/Wikode/wikodeApp/tests.py
  Project/Wikode/wikodeApp/utils/textSearch.py
  Project/Wikode/wikodeApp/views.py
Labels: bug, backend, effort: 2, priority: Blocker, frontend

#102 Refactor tag the whole article feature. #67
  Project/Wikode/templates/wikodeApp/articleDetail.html
  Project/Wikode/wikodeApp/tests.py
Labels: backend, effort: 3, testing

#106 Feature/tag fragment of article
  Project/Wikode/templates/wikodeApp/articleDetail.html
  Project/Wikode/wikodeApp/models.py
  Project/Wikode/wikodeApp/static/wikodeApp/css/styles.css
  Project/Wikode/wikodeApp/static/wikodeApp/js/articleDetail.js
  Project/Wikode/wikodeApp/utils/articleManager.py
  Project/Wikode/wikodeApp/utils/fetchArticles.py
  Project/Wikode/wikodeApp/utils/wikiManager.py
  Project/Wikode/wikodeApp/views.py
Labels: backend, effort: 5, priority: Blocker, frontend

#111 Feature/annotation activities
  Project/Wikode/wikodeApp/utils/activityManager.py
  Project/Wikode/wikodeApp/views.py
Labels: enhancement, backend, effort: 1, priority: Low

#133 Bugfix/histogram refinement
  Project/Wikode/templates/wikodeApp/searchResults.html
  Project/Wikode/wikodeApp/views.py
Labels: bug, effort: 2

#125 Feature/follow
  Project/Wikode/templates/wikodeApp/homePage.html
  Project/Wikode/templates/wikodeApp/profilePage.html
  Project/Wikode/wikodeApp/admin.py
  Project/Wikode/wikodeApp/models.py
  Project/Wikode/wikodeApp/static/wikodeApp/js/profilePage.js
  Project/Wikode/wikodeApp/tests.py
  Project/Wikode/wikodeApp/urls.py
  Project/Wikode/wikodeApp/utils/followManager.py
  Project/Wikode/wikodeApp/views.py
Labels: backend, effort: 5, priority: High, frontend

#136 Feature/upvote downvote tag
  Project/Wikode/templates/wikodeApp/articleDetail.html
  Project/Wikode/wikodeApp/models.py
  Project/Wikode/wikodeApp/static/wikodeApp/js/articleDetail.js
  Project/Wikode/wikodeApp/urls.py
  Project/Wikode/wikodeApp/utils/voteManager.py
  Project/Wikode/wikodeApp/views.py
Labels: backend, effort: 3, priority: Low, frontend

#146 Bug/feed url redirect
  Project/Wikode/templates/wikodeApp/homePage.html
  Project/Wikode/templates/wikodeApp/profilePage.html
  Project/Wikode/wikodeApp/utils/feedDTO.py
  Project/Wikode/wikodeApp/views.py
Labels: bug, backend, effort: 1, priority: Blocker, frontend

#147 Add "part of" relation for wiki items. #135
  Project/Wikode/wikodeApp/utils/wikiManager.py
Labels: enhancement, backend, effort: 1, priority: Low

#149 activity manager change registrationApplication to User model
  Project/Wikode/wikodeApp/utils/activityManager.py
Labels: bug, backend, effort: 1, priority: Blocker

#143 Develop to main
  Project/Wikode/Wikode/wsgi.py
  Project/Wikode/templates/wikodeApp/articleDetail.html
  Project/Wikode/templates/wikodeApp/base.html
  Project/Wikode/templates/wikodeApp/homePage.html
  Project/Wikode/templates/wikodeApp/profilePage.html
  Project/Wikode/templates/wikodeApp/registrationRequests.html
  Project/Wikode/templates/wikodeApp/searchResults.html
  Project/Wikode/wikodeApp/admin.py
  Project/Wikode/wikodeApp/models.py
  Project/Wikode/wikodeApp/static/wikodeApp/css/styles.css
  Project/Wikode/wikodeApp/static/wikodeApp/js/articleDetail.js
  Project/Wikode/wikodeApp/static/wikodeApp/js/index.js
  Project/Wikode/wikodeApp/static/wikodeApp/js/profilePage.js
  Project/Wikode/wikodeApp/tests.py
  Project/Wikode/wikodeApp/urls.py
  Project/Wikode/wikodeApp/utils/activityManager.py
  Project/Wikode/wikodeApp/utils/feedDTO.py
  Project/Wikode/wikodeApp/utils/followManager.py
  Project/Wikode/wikodeApp/utils/voteManager.py
  Project/Wikode/wikodeApp/utils/wikiManager.py
  Project/Wikode/wikodeApp/views.py
Labels: devops, priority: High

#150 Feature/error screen
  Project/Wikode/Wikode/urls.py
  Project/Wikode/templates/wikodeApp/error.html
  Project/Wikode/wikodeApp/static/wikodeApp/css/error.css
  Project/Wikode/wikodeApp/views.py
Labels: enhancement, backend, effort: 2, priority: High, frontend

#156 Suggestion model added
  Project/Wikode/wikodeApp/models.py
Labels: backend, effort: 1, priority: Blocker

#159 Feature/save vote activity
  Project/Wikode/wikodeApp/utils/activityManager.py
  Project/Wikode/wikodeApp/utils/voteManager.py
  Project/Wikode/wikodeApp/views.py
Labels: enhancement, backend, effort: 1, priority: Low

#162 Feature/change tag view
  Project/Wikode/templates/wikodeApp/articleDetail.html
  Project/Wikode/wikodeApp/models.py
  Project/Wikode/wikodeApp/static/wikodeApp/js/articleDetail.js
  Project/Wikode/wikodeApp/views.py
Labels: effort: 3, priority: High, frontend

#160 Add clear tag fragment button. #107
  Project/Wikode/templates/wikodeApp/articleDetail.html
  Project/Wikode/wikodeApp/static/wikodeApp/js/articleDetail.js
Labels: enhancement, effort: 2, priority: Low, frontend

#163 Feature/refactor activity and annotation models
  Project/Wikode/wikodeApp/models.py
  Project/Wikode/wikodeApp/utils/activityManager.py
  Project/Wikode/wikodeApp/views.py
Labels: backend, effort: 2, priority: Low

#164 Add scroll to tag list table in article detail.
  Project/Wikode/templates/wikodeApp/articleDetail.html
  Project/Wikode/wikodeApp/static/wikodeApp/css/bootstrap-tagsinput.css
Labels: enhancement, frontend

#165 Feature/free annotation
  Project/Wikode/templates/wikodeApp/articleDetail.html
  Project/Wikode/templates/wikodeApp/base.html
  Project/Wikode/wikodeApp/models.py
  Project/Wikode/wikodeApp/static/wikodeApp/css/popup-form.css
  Project/Wikode/wikodeApp/static/wikodeApp/css/styles.css
  Project/Wikode/wikodeApp/static/wikodeApp/js/articleDetail.js
  Project/Wikode/wikodeApp/utils/activityManager.py
  Project/Wikode/wikodeApp/utils/feedDTO.py
  Project/Wikode/wikodeApp/utils/wikiManager.py
  Project/Wikode/wikodeApp/views.py
Labels: enhancement, backend, effort: 3, priority: Blocker

#169 Remove duplication in cancelling article tag. #168
  Project/Wikode/wikodeApp/static/wikodeApp/js/articleDetail.js
Labels: effort: 1, priority: High, frontend
