Repository CAKES-coding/swe574-group2, pull requests merged in 2022-01, with the labels that each got.

#173 Feature/suggestion interval
  Project/Wikode/templates/wikodeApp/homePage.html
  Project/Wikode/wikodeApp/models.py
  Project/Wikode/wikodeApp/utils/articleSuggestionDTO.py
  Project/Wikode/wikodeApp/utils/suggestionManager.py
  Project/Wikode/wikodeApp/utils/userSuggestionDTO.py
  Project/Wikode/wikodeApp/views.py
Labels: effort: 3, priority: High, frontend

#177 Feature/inc tags to text search
  Project/Wikode/templates/wikodeApp/searchResults.html
  Project/Wikode/wikodeApp/utils/textSearch.py
  external_resources/installation/docker-compose.yml
Labels: enhancement, backend, effort: 5, priority: High

#182 Fix article url bug in feeds for vote activities. #171
  Project/Wikode/wikodeApp/utils/activityManager.py
  Project/Wikode/wikodeApp/views.py
Labels: bug, priority: Low, frontend

#184 Bugfix/test errors
  Project/Wikode/wikodeApp/tests.py
Labels: testing

#189 Feature/tagging tooltips
  Project/Wikode/templates/wikodeApp/articleDetail.html
  Project/Wikode/templates/wikodeApp/base.html
  Project/Wikode/wikodeApp/forms.py
  Project/Wikode/wikodeApp/models.py
  Project/Wikode/wikodeApp/static/wikodeApp/css/balloon.css
  Project/Wikode/wikodeApp/utils/activityManager.py
  Project/Wikode/wikodeApp/utils/feedDTO.py
Labels: enhancement, effort: 1, priority: Low, frontend

#190 Add ready to use docker-compose file.
  installation/customizable/docker-compose.yml
  installation/installation.md
  installation/ready to use/docker-compose.yml
Labels: documentation, devops, effort: 2, priority: Low
